### ISSUE TITLE
Deploy site to cloud provider

### ISSUE THREAD

**Issue by mtvillwock** [mtvillwock/dopamenu#2]
Per @jacobmoyle:

```
Like two years ago, my co worker who has over 20 years of experience (and consistently blows my mind with architecture stuff), really just recommended learning the following (which applies to all cloud providers):

He recommended using terraform (and there’s minimal guides for this around), but essentially this gets you 80% of the way into cloud. Just a matter of layering on queue calls, deploying a separate dockerized service, and getting them to talk to one another. All other services are layers on top of this.

- Create a user with only required permissions to access a service 

Programmatically:
- Deploy a lambda (a “hello world” “API”) with a url that can be invoked by the command line
- Scale said lambda to two different regions
- Add a VPC
- Add a redis cache (e.g. simple lookup, just focus on the connection)
```

### TODO

- [ ] [Set up a user on AWS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html)
- [ ] [Create and deploy a Lambda on AWS](https://medium.com/@corymaklin/tutorial-amazon-web-services-part-3-lambda-functions-with-aws-cli-ba9f53c5f5ec)
- [ ] [Scale lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-concurrency.html) to 2 different regions
- [ ] Add a [VPC](cloudflare.com/learning/cloud/what-is-a-virtual-private-cloud)
- [ ] [Add a Redis cache](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/LambdaRedis.html) (just a simple lookup, focus on the connection)
